#Build and test are stages that belong in the stages section below but aren't currently working.
# - build
# - test
 
stages:
  - deploy

variables:
  IMAGE_NAME: "wordpress"
  IMAGE_TAG: "latest"
  GITHUB_PROJECT: "p42/s6-wordpress-docker.git"

before_script:
  - docker info

# build-master:
#   stage: build
#   script:
#     - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
#   only:
#     - master

# test-master:
#   stage: test
#   script:
#     - docker run --rm "${IMAGE_NAME}:${IMAGE_TAG}" /bin/true
#   only:
#     - master

# test:
#   stage: test
#   script:
#     - docker run --rm "${IMAGE_NAME}:${IMAGE_TAG}" /bin/true
#   except:
#     - master

# build:
#   stage: build
#   script:
#     - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
#   except:
#     - master

deploy_to_github:
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} master
  only:
    - master

deploy_tags_to_github:
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} master --tags
  only:
    - tags
