version: '2'

services:

  wordpress:
    container_name: centos_wpcompose
    image: local/centos-wp
    ports:
      - 80:80
      # - 443:443
    volumes:
      - /tmp/wp-content/plugins:/var/www/html/wordpress/wp-content/plugins
      - /tmp/wp-content/themes:/var/www/html/wordpress/wp-content/themes
    restart: always
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    # ports:
    #   - 3306:3306
    volumes:
      - /tmp/mariadb/:/var/lib
    # env_file:
    #   - db_variables.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress