version: '2'
volumes:
  wpdatabcone:
    external: true
    driver: rancher-nfs
services:
  wordpress2:
    image: project42/wordpress
    environment:
      DATABASE_PREFIX_ENV: wp_
      MYSQL_DATABASE_ENV: wordpress
      MYSQL_PASSWORD_ENV: wordpress
      MYSQL_USER_ENV: wordpress
      URL_ENV: mydevsite.com
    stdin_open: true
    volumes:
    - wpdatabcone:/var/www/html/wordpress/wp-content
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: role=worker
      io.rancher.sidekicks: crontab
      io.rancher.container.pull_image: always
      'io.rancher.scheduler.affinity:host_label: role': worker
    external_links:
    - mysql/external-mysql:mysql
  crontab:
    image: project42/centos-gitcron
    working_dir: /var/www/html/wordpress/wp-content/
    entrypoint:
    - /bin/sh
    volumes_from:
    - wordpress2
    command:
    - '/scripts/git_commands.sh,'
    - /var/www/html/wordpress/wp-content
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      cron.schedule: '''@hourly'''
      'io.rancher.scheduler.affinity:host_label: role': worker
  Wordpress-LB:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 10030:10030/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: role=service
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'